apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  creationTimestamp: null
  name: pctl-profile-weaveworks-nginx-nginx-chart
  namespace: 75d0784b-365d-45d6-b7ee-7142efabe139
spec:
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: HelmRepository
        name: pctl-profile-profiles-examples-nginx
        namespace: 75d0784b-365d-45d6-b7ee-7142efabe139
      version: 9.3.0
  interval: 0s
  valuesFrom:
  - kind: ConfigMap
    name: pctl-profile-nginx-chart-defaultvalues
    valuesKey: default-values.yaml
  - kind: ConfigMap
    name: pprof-values
    valuesKey: nginx-chart
status: {}
