apiVersion: v1
data:
  default-values.yaml: |
    replicaCount: 3
    service:
      type: ClusterIP
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: pctl-profile-bitnami-nginx-defaultvalues
  namespace: fc2337c6-b1d9-4fb7-9359-0ffd21d7ec4f
