apiVersion: v1
data:
  default-values.yaml: |
    master:
      persistence:
        enabled: false
    replica:
      replicaCount: 0
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: pprof-dependon-chart-defaultvalues
  namespace: 7d61c337-bf3b-4739-a9a4-95e167e90928
