apiVersion: v1
data:
  default-values.yaml: |
    replicaCount: 3
    service:
      type: ClusterIP
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: pctl-profile-bitnami-nginx-defaultvalues
  namespace: 479e679e-2a2f-454e-8085-dde01ef74a18
