apiVersion: v1
data:
  default-values.yaml: |
    replicaCount: 3
    service:
      type: ClusterIP
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: pctl-profile-bitnami-nginx-defaultvalues
  namespace: 432deb2c-c356-40af-9a4d-13c793a907f5
