apiVersion: v1
data:
  default-values.yaml: |
    replicaCount: 3
    service:
      type: ClusterIP
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: pctl-profile-bitnami-nginx-defaultvalues
  namespace: 33e7819b-376e-47ff-a2bd-0a038be11270
