apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  creationTimestamp: null
  name: pctl-profile-nginx-bitnami-nginx
  namespace: c3528c28-6676-426a-a6d1-90fcf6a4a161
spec:
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: HelmRepository
        name: pctl-profile-nginx-profile-nginx
        namespace: c3528c28-6676-426a-a6d1-90fcf6a4a161
      version: 8.9.1
  interval: 0s
  valuesFrom:
  - kind: ConfigMap
    name: pctl-profile-bitnami-nginx-defaultvalues
    valuesKey: default-values.yaml
status: {}
