apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  creationTimestamp: null
  name: pctl-profile-nginx-bitnami-nginx
  namespace: f1026996-2b0f-4418-9205-c9a20cbc8218
spec:
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: HelmRepository
        name: pctl-profile-nginx-profile-nginx
        namespace: f1026996-2b0f-4418-9205-c9a20cbc8218
      version: 8.9.1
  interval: 0s
  valuesFrom:
  - kind: ConfigMap
    name: pctl-profile-bitnami-nginx-defaultvalues
    valuesKey: default-values.yaml
status: {}
