apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  creationTimestamp: null
  name: pctl-profile-nginx-bitnami-nginx
  namespace: 479e679e-2a2f-454e-8085-dde01ef74a18
spec:
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: HelmRepository
        name: pctl-profile-nginx-profile-nginx
        namespace: 479e679e-2a2f-454e-8085-dde01ef74a18
      version: 8.9.1
  interval: 0s
  valuesFrom:
  - kind: ConfigMap
    name: pctl-profile-bitnami-nginx-defaultvalues
    valuesKey: default-values.yaml
status: {}
