apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  creationTimestamp: null
  name: pctl-profile-weaveworks-nginx-dependon-chart
  namespace: 75d0784b-365d-45d6-b7ee-7142efabe139
spec:
  dependsOn:
  - name: pctl-profile-weaveworks-nginx-nginx-deployment
    namespace: 75d0784b-365d-45d6-b7ee-7142efabe139
  - name: pctl-profile-weaveworks-nginx-nginx-chart
    namespace: 75d0784b-365d-45d6-b7ee-7142efabe139
  healthChecks:
  - apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    name: pctl-profile-weaveworks-nginx-dependon-chart
    namespace: 75d0784b-365d-45d6-b7ee-7142efabe139
  interval: 5m0s
  path: artifacts/dependon-chart/helm-chart
  prune: true
  sourceRef:
    kind: GitRepository
    name: pctl-repo
    namespace: 75d0784b-365d-45d6-b7ee-7142efabe139
  targetNamespace: 75d0784b-365d-45d6-b7ee-7142efabe139
status: {}
