apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  creationTimestamp: null
  name: pctl-profile-bitnami-nginx-nginx-server
  namespace: 75d0784b-365d-45d6-b7ee-7142efabe139
spec:
  healthChecks:
  - apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    name: pctl-profile-bitnami-nginx-nginx-server
    namespace: 75d0784b-365d-45d6-b7ee-7142efabe139
  interval: 5m0s
  path: artifacts/nested-profile/nginx-server/helm-chart
  prune: true
  sourceRef:
    kind: GitRepository
    name: pctl-repo
    namespace: 75d0784b-365d-45d6-b7ee-7142efabe139
  targetNamespace: 75d0784b-365d-45d6-b7ee-7142efabe139
status: {}
