apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  creationTimestamp: null
  name: pprof-weaveworks-nginx-nginx-deployment
  namespace: 7d61c337-bf3b-4739-a9a4-95e167e90928
spec:
  interval: 5m0s
  path: artifacts/nginx-deployment/nginx/deployment
  prune: true
  sourceRef:
    kind: GitRepository
    name: pctl-repo
    namespace: 7d61c337-bf3b-4739-a9a4-95e167e90928
  targetNamespace: 7d61c337-bf3b-4739-a9a4-95e167e90928
status: {}
